"use client";
import {useEffect,useState} from "react";
import {ArrowDownRight,ArrowUpRight,PiggyBank,WalletCards} from "lucide-react";
import {DashboardSkeleton} from "@/components/dashboard/dashboard-skeleton";
import {EmptyDashboard} from "@/components/dashboard/empty-dashboard";
import {formatNumber} from "@/lib/finance/currency";
import type {Navigate} from "@/components/budgetbuddy/view-types";
type Data={summary:{balance:number;income:number;expenses:number;savingsRate:number};categories:{name:string;value:number}[];recent:{id:string;title:string;type:"income"|"expense";amount:number;transaction_date:string;category:{name:string}|{name:string}[]|null}[]};
const Stat=({name,value,Icon}:{name:string;value:string;Icon:typeof WalletCards})=><article className="stat"><i><Icon/></i><span>{name}</span><strong>{value}</strong></article>;
export function DashboardScreen({go}:{go:Navigate}){const [data,setData]=useState<Data|null>(null),[error,setError]=useState(false);useEffect(()=>{void fetch("/api/dashboard",{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error();setData(await r.json() as Data);}).catch(()=>setError(true));},[]);if(!data&&!error)return <DashboardSkeleton/>;if(error)return <div className="panel">Unable to load your dashboard.</div>;if(!data?.recent.length)return <EmptyDashboard language="en" onAddTransaction={()=>go("transactions")}/>;return <><div className="stats"><Stat name="Total balance" value={`₺${formatNumber(data.summary.balance,"en")}`} Icon={WalletCards}/><Stat name="Monthly income" value={`₺${formatNumber(data.summary.income,"en")}`} Icon={ArrowUpRight}/><Stat name="Monthly expenses" value={`₺${formatNumber(data.summary.expenses,"en")}`} Icon={ArrowDownRight}/><Stat name="Savings rate" value={`${data.summary.savingsRate.toFixed(1)}%`} Icon={PiggyBank}/></div><div className="dash"><article className="panel"><div className="panel-head"><div><h3>Spending by category</h3><p>Current month</p></div></div><div className="live-list">{data.categories.length?data.categories.map((c,i)=><div key={c.name}><i style={{background:["#5267df","#249779","#f18470","#d7a33c"][i%4]}}/>{c.name}<b>₺{formatNumber(c.value,"en")}</b></div>):<p>No expenses this month.</p>}</div></article><article className="panel"><div className="panel-head"><div><h3>Recent transactions</h3><p>Latest activity</p></div></div><div className="live-list">{data.recent.map(x=>{const category=Array.isArray(x.category)?x.category[0]:x.category;return <div key={x.id}><span><b>{x.title}</b><small>{category?.name??"Uncategorized"} · {x.transaction_date}</small></span><b className={x.type==="income"?"pos":"neg"}>{x.type==="income"?"+":"−"}₺{formatNumber(x.amount,"en")}</b></div>;})}</div></article></div></>;}
