"use client";

import { useContext, useEffect, useState } from "react";
import { CheckCircle2, Pencil, Plus, Target, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { LanguageContext, useT } from "@/components/providers/language-provider";
import { formatCurrency } from "@/lib/finance/currency";
import type { Currency } from "@/types/finance";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { AllowancePlan } from "@/components/budgetbuddy/allowance-plan";

type Goal = { id: string; name: string; target_amount: number; current_amount: number; deadline: string | null; sharedFamilyGroupIds?: string[] };
type GoalDraft = { name: string; targetAmount: string; deadline: string };
const emptyDraft: GoalDraft = { name: "", targetAmount: "", deadline: "" };

export function GoalsScreen() {
  const t = useT(); const { language } = useContext(LanguageContext); const tr = language === "tr";
  const [goals, setGoals] = useState<Goal[]>([]); const [currency, setCurrency] = useState<Currency>("TRY"); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const [editorOpen, setEditorOpen] = useState(false); const [editing, setEditing] = useState<Goal | null>(null); const [draft, setDraft] = useState<GoalDraft>(emptyDraft);
  const [progressGoal, setProgressGoal] = useState<Goal | null>(null); const [progressAmount, setProgressAmount] = useState(""); const [deleteGoal, setDeleteGoal] = useState<Goal | null>(null);
  const [familyGroups, setFamilyGroups] = useState<{ id: string; name: string }[]>([]);

  useEffect(() => { let active = true; void fetch("/api/goals", { cache: "no-store" }).then(async (response) => { const payload = await response.json() as { goals?: Goal[]; currency?: Currency; error?: string }; if (!response.ok) throw new Error(payload.error); if (active) { setGoals(payload.goals ?? []); setCurrency(payload.currency ?? "TRY"); } }).catch(() => { if (active) setError(tr ? "Hedefler yüklenemedi. Lütfen tekrar deneyin." : "Unable to load goals. Please try again."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [tr]);
  useEffect(() => { void fetch("/api/family", { cache: "no-store" }).then(async (response) => response.ok ? await response.json() as { groups?: { id: string; name: string }[] } : null).then((data) => setFamilyGroups(data?.groups ?? [])).catch(() => undefined); if (new URLSearchParams(window.location.search).get("create") === "1") { const timer = window.setTimeout(() => setEditorOpen(true), 0); return () => window.clearTimeout(timer); } }, []);
  const openCreate = () => { setEditing(null); setDraft(emptyDraft); setEditorOpen(true); };
  const openEdit = (goal: Goal) => { setEditing(goal); setDraft({ name: goal.name, targetAmount: String(goal.target_amount), deadline: goal.deadline ?? "" }); setEditorOpen(true); };
  const replaceGoal = (goal: Goal) => setGoals((current) => current.map((item) => item.id === goal.id ? { ...goal, sharedFamilyGroupIds: item.sharedFamilyGroupIds } : item));
  const toggleShare = async (goal: Goal, familyGroupId: string) => { const shared = !(goal.sharedFamilyGroupIds ?? []).includes(familyGroupId); try { const response = await fetch(`/api/goals/${goal.id}/share`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ familyGroupId, shared }) }); if (!response.ok) throw new Error(); setGoals((current) => current.map((item) => item.id === goal.id ? { ...item, sharedFamilyGroupIds: shared ? [...(item.sharedFamilyGroupIds ?? []), familyGroupId] : (item.sharedFamilyGroupIds ?? []).filter((id) => id !== familyGroupId) } : item)); toast.success(shared ? (tr ? "Hedef ilerlemesi paylaşıldı." : "Goal progress shared.") : (tr ? "Paylaşım kapatıldı." : "Sharing stopped.")); } catch { toast.error(tr ? "Paylaşım değiştirilemedi." : "Unable to change sharing."); } };
  const saveGoal = async () => { setSaving(true); setError(null); try { const response = await fetch(editing ? `/api/goals/${editing.id}` : "/api/goals", { method: editing ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(draft) }); const payload = await response.json() as { goal?: Goal; error?: string }; if (!response.ok || !payload.goal) throw new Error(); if (editing) replaceGoal(payload.goal); else setGoals((current) => [payload.goal!, ...current]); setEditorOpen(false); toast.success(tr ? "Hedef kaydedildi." : "Goal saved."); } catch { const message = tr ? "Hedef kaydedilemedi. Alanları kontrol edip tekrar deneyin." : "Unable to save the goal. Check the fields and try again."; setError(message); toast.error(message); } finally { setSaving(false); } };
  const updateProgress = async (complete = false) => { if (!progressGoal) return; setSaving(true); try { const response = await fetch(`/api/goals/${progressGoal.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(complete ? { currentAmount: progressGoal.target_amount } : { addAmount: progressAmount }) }); const payload = await response.json() as { goal?: Goal; error?: string }; if (!response.ok || !payload.goal) throw new Error(); replaceGoal(payload.goal); setProgressGoal(null); setProgressAmount(""); toast.success(complete ? (tr ? "Hedef tamamlandı." : "Goal completed.") : (tr ? "İlerleme eklendi." : "Progress added.")); } catch { toast.error(tr ? "Hedef ilerlemesi güncellenemedi. Lütfen tekrar deneyin." : "Unable to update goal progress. Please try again."); } finally { setSaving(false); } };
  const remove = async () => { if (!deleteGoal) return; const response = await fetch(`/api/goals/${deleteGoal.id}`, { method: "DELETE" }); if (!response.ok) { toast.error(tr ? "Hedef silinemedi." : "Unable to delete the goal."); return; } setGoals((current) => current.filter((item) => item.id !== deleteGoal.id)); setDeleteGoal(null); toast.success(tr ? "Hedef silindi." : "Goal deleted."); };
  const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat(tr ? "tr-TR" : "en-US", { dateStyle: "medium" }).format(new Date(`${value}T00:00:00`)) : (tr ? "Hedef tarih yok" : "No target date");

  return <>
    <AllowancePlan />
    <div className="page-head"><div><h2>{t("Your savings goals")}</h2><p>{t("Big plans become easier when progress is visible.")}</p></div><Button onClick={openCreate}><Plus />{t("Create goal")}</Button></div>
    {error && <p className="form-error" role="alert">{error}</p>}
    {loading ? <div className="panel">{tr ? "Hedefler yükleniyor…" : "Loading goals…"}</div> : goals.length === 0 ? <div className="panel empty-accounts"><Target /><h3>{tr ? "Henüz hedef yok" : "No goals yet"}</h3><p>{tr ? "İlk hedefin için banka hesabı veya geçmiş işlem eklemen gerekmez." : "No bank account or past transactions are needed for your first goal."}</p><Button onClick={openCreate}><Plus />{t("Create goal")}</Button></div> : <div className="goal-grid">{goals.map((goal, index) => { const current = Number(goal.current_amount); const target = Number(goal.target_amount); const percent = Math.min(100, Math.round(current / target * 100)); const complete = current >= target; return <article className={`panel goal ${complete ? "goal-complete" : ""}`} key={goal.id}><div className={`goal-art g${index % 3}`}>{complete ? <CheckCircle2 /> : <Target />}</div><div className="goal-actions"><button type="button" aria-label={tr ? "Hedefi düzenle" : "Edit goal"} onClick={() => openEdit(goal)}><Pencil /></button><button type="button" aria-label={tr ? "Hedefi sil" : "Delete goal"} onClick={() => setDeleteGoal(goal)}><Trash2 /></button></div><h3>{goal.name}</h3><p>{t("Target date")} · {formatDate(goal.deadline)}</p><b>{formatCurrency(current, currency, language)} <span>{t("of")} {formatCurrency(target, currency, language)}</span></b><Progress value={percent} /><small>{complete ? (tr ? "Tamamlandı" : "Completed") : `${percent}% ${t("complete")}`}<span>{formatCurrency(Math.max(0, target - current), currency, language)} {t("to go")}</span></small><Button variant={complete ? "secondary" : "outline"} disabled={complete} onClick={() => { setProgressGoal(goal); setProgressAmount(""); }}>{complete ? (tr ? "Hedef tamamlandı" : "Goal completed") : t("Update progress")}</Button>{familyGroups.length > 0 && <div className="mt-3 border-t border-[#e8eaf0] pt-3"><p className="mb-2 text-xs text-[#737c91]">{tr ? "Yalnızca hedef adı ve ilerleme yüzdesi paylaşılır." : "Only the name and progress percentage are shared."}</p>{familyGroups.map((group) => <button key={group.id} type="button" className="mb-1 block text-xs font-semibold text-[#4258d5] hover:underline" onClick={() => void toggleShare(goal, group.id)}>{(goal.sharedFamilyGroupIds ?? []).includes(group.id) ? (tr ? `${group.name} · paylaşımı kapat` : `${group.name} · stop sharing`) : (tr ? `${group.name} ile paylaş` : `Share with ${group.name}`)}</button>)}</div>}</article>; })}</div>}

    <Dialog open={editorOpen} onOpenChange={setEditorOpen}><DialogContent><DialogHeader><DialogTitle>{editing ? (tr ? "Hedefi düzenle" : "Edit goal") : t("Create goal")}</DialogTitle><DialogDescription>{tr ? "Hedef tutarını ve isteğe bağlı bitiş tarihini belirleyin." : "Set a target amount and an optional target date."}</DialogDescription></DialogHeader><div className="goal-form"><label>{tr ? "Ad" : "Name"}<Input value={draft.name} minLength={2} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label>{tr ? "Hedef tutar" : "Target amount"}<Input value={draft.targetAmount} type="number" min="1" step="0.01" onChange={(event) => setDraft({ ...draft, targetAmount: event.target.value })} /></label><label>{t("Target date")}<Input value={draft.deadline} type="date" onChange={(event) => setDraft({ ...draft, deadline: event.target.value })} /></label><Button disabled={saving || draft.name.trim().length < 2 || !draft.targetAmount} onClick={() => void saveGoal()}>{saving ? t("Saving…") : t("Save changes")}</Button></div></DialogContent></Dialog>
    <Dialog open={Boolean(progressGoal)} onOpenChange={(open) => { if (!open) setProgressGoal(null); }}><DialogContent><DialogHeader><DialogTitle>{t("Update progress")}</DialogTitle><DialogDescription>{progressGoal?.name}</DialogDescription></DialogHeader><div className="goal-form"><label>{tr ? "Eklenecek tutar" : "Amount to add"}<Input autoFocus value={progressAmount} type="number" min="0.01" step="0.01" onChange={(event) => setProgressAmount(event.target.value)} /></label><Button disabled={saving || !progressAmount} onClick={() => void updateProgress()}><Plus />{tr ? "İlerleme ekle" : "Add progress"}</Button><Button variant="outline" disabled={saving} onClick={() => void updateProgress(true)}><CheckCircle2 />{tr ? "Tamamlandı olarak işaretle" : "Mark as completed"}</Button></div></DialogContent></Dialog>
    <AlertDialog open={Boolean(deleteGoal)} onOpenChange={(open) => { if (!open) setDeleteGoal(null); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{tr ? "Bu hedef silinsin mi?" : "Delete this goal?"}</AlertDialogTitle><AlertDialogDescription>{tr ? "Hedef ve kayıtlı ilerleme kalıcı olarak silinir." : "The goal and its saved progress will be permanently removed."}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{t("Cancel")}</AlertDialogCancel><AlertDialogAction onClick={() => void remove()}>{t("Delete")}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </>;
}
